/* Automated test driver for Lab 05. DO NOT EDIT THIS FILE. */
public class Lab05LoopBasicsTest {

    public static void main(String[] args) {

        String out1 = TestRunner.runMain(Lab05LoopBasics::main, "10\n7\n4 8 15 -1\n");
        TestRunner.section("Case 1 - n=10, multiplier=7, values 4 8 15");
        TestRunner.checkOutputContains("Sum 1..10 = 55", out1, "Sum 1 to 10: 55");
        TestRunner.checkOutputContains("Table row for 7", out1, "7 14 21 28 35 42 49 56 63");
        TestRunner.checkOutputContains("Count excludes the sentinel", out1, "Count: 3");
        TestRunner.checkOutputContains("Average of 4, 8, 15", out1, "Average: 9.00");

        String out2 = TestRunner.runMain(Lab05LoopBasics::main, "5\n3\n10 20 -1\n");
        TestRunner.section("Case 2 - n=5, multiplier=3, values 10 20");
        TestRunner.checkOutputContains("Sum 1..5 = 15", out2, "Sum 1 to 5: 15");
        TestRunner.checkOutputContains("Table row for 3", out2, "3 6 9 12 15 18 21 24 27");
        TestRunner.checkOutputContains("Count", out2, "Count: 2");
        TestRunner.checkOutputContains("Average", out2, "Average: 15.00");

        String out3 = TestRunner.runMain(Lab05LoopBasics::main, "1\n9\n-1\n");
        TestRunner.section("Case 3 - edge cases: n=1 and sentinel entered immediately");
        TestRunner.checkOutputContains("Sum 1..1 = 1", out3, "Sum 1 to 1: 1");
        TestRunner.checkOutputContains("Table row for 9", out3, "9 18 27 36 45 54 63 72 81");
        TestRunner.checkOutputContains("Count is zero", out3, "Count: 0");
        TestRunner.checkOutputContains("Division by zero is guarded", out3, "Average: N/A");

        String out4 = TestRunner.runMain(Lab05LoopBasics::main, "100\n12\n-1\n");
        TestRunner.section("Case 4 - n=100 (the classic Gauss sum)");
        TestRunner.checkOutputContains("Sum 1..100 = 5050", out4, "Sum 1 to 100: 5050");

        TestRunner.exitWithSummary();
    }
}
